package br.com.vertice.emerion_dashboard.domain.customerorder.model

import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate

/**
 * Domain model for a customer order (header + line items). Plain Kotlin, no
 * JPA/Jakarta/OpenAPI annotations — this is what use cases and ports
 * operate on.
 */
data class CustomerOrder(
    val id: Long?,
    val externalId: String,
    val codCli: String,
    val cnpjEmpresa: String,
    val cpfCnpj: String?,
    val nronfe: String?,
    val dteres: LocalDate,
    val sitres: String?,
    val totger: BigDecimal,
    val totres: BigDecimal,
    val totipi: BigDecimal,
    val totsub: BigDecimal,
    val totdescinc: BigDecimal,
    val totfrt: BigDecimal? = null,
    val totseg: BigDecimal? = null,
    val totoutdesp: BigDecimal? = null,
    val vendedorExternalId: Long? = null,
    val atendenteCod: String? = null,
    val dataEntregaPrevista: LocalDate? = null,
    val descontoComercial: BigDecimal? = null,
    val descontoRegional: BigDecimal? = null,
    val codigoTransportadora: String? = null,
    val linhaReserva: String? = null,
    val pedidoAnterior: String? = null,
    val regimeTributario: String? = null,
    val nomeRegimeTributario: String? = null,
    val itens: List<CustomerOrderItem>,
    val createdAt: Instant,
    val updatedAt: Instant,
) {
    companion object {
        /** Factory for a brand-new order coming from ingestion (no id yet). */
        fun newFromIngestion(
            externalId: String,
            codCli: String,
            cnpjEmpresa: String,
            cpfCnpj: String?,
            nronfe: String?,
            dteres: LocalDate,
            sitres: String?,
            totger: BigDecimal,
            totres: BigDecimal,
            totipi: BigDecimal,
            totsub: BigDecimal,
            totdescinc: BigDecimal,
            totfrt: BigDecimal? = null,
            totseg: BigDecimal? = null,
            totoutdesp: BigDecimal? = null,
            vendedorExternalId: Long? = null,
            atendenteCod: String? = null,
            dataEntregaPrevista: LocalDate? = null,
            descontoComercial: BigDecimal? = null,
            descontoRegional: BigDecimal? = null,
            codigoTransportadora: String? = null,
            linhaReserva: String? = null,
            pedidoAnterior: String? = null,
            regimeTributario: String? = null,
            nomeRegimeTributario: String? = null,
            itens: List<CustomerOrderItem>,
            now: Instant,
        ) = CustomerOrder(
            id = null,
            externalId = externalId,
            codCli = codCli,
            cnpjEmpresa = cnpjEmpresa,
            cpfCnpj = cpfCnpj,
            nronfe = nronfe,
            dteres = dteres,
            sitres = sitres,
            totger = totger,
            totres = totres,
            totipi = totipi,
            totsub = totsub,
            totdescinc = totdescinc,
            totfrt = totfrt,
            totseg = totseg,
            totoutdesp = totoutdesp,
            vendedorExternalId = vendedorExternalId,
            atendenteCod = atendenteCod,
            dataEntregaPrevista = dataEntregaPrevista,
            descontoComercial = descontoComercial,
            descontoRegional = descontoRegional,
            codigoTransportadora = codigoTransportadora,
            linhaReserva = linhaReserva,
            pedidoAnterior = pedidoAnterior,
            regimeTributario = regimeTributario,
            nomeRegimeTributario = nomeRegimeTributario,
            itens = itens,
            createdAt = now,
            updatedAt = now,
        )
    }

    /**
     * Applies an ingestion update on top of an existing order, bumping
     * updatedAt. The `itens` list is replaced wholesale, matching the
     * source system's contract of always sending the order's complete line
     * items in a single payload.
     */
    fun mergeFromIngestion(
        codCli: String,
        cnpjEmpresa: String,
        cpfCnpj: String?,
        nronfe: String?,
        dteres: LocalDate,
        sitres: String?,
        totger: BigDecimal,
        totres: BigDecimal,
        totipi: BigDecimal,
        totsub: BigDecimal,
        totdescinc: BigDecimal,
        totfrt: BigDecimal? = null,
        totseg: BigDecimal? = null,
        totoutdesp: BigDecimal? = null,
        vendedorExternalId: Long? = null,
        atendenteCod: String? = null,
        dataEntregaPrevista: LocalDate? = null,
        descontoComercial: BigDecimal? = null,
        descontoRegional: BigDecimal? = null,
        codigoTransportadora: String? = null,
        linhaReserva: String? = null,
        pedidoAnterior: String? = null,
        regimeTributario: String? = null,
        nomeRegimeTributario: String? = null,
        itens: List<CustomerOrderItem>,
        now: Instant,
    ) = copy(
        codCli = codCli,
        cnpjEmpresa = cnpjEmpresa,
        cpfCnpj = cpfCnpj,
        nronfe = nronfe,
        dteres = dteres,
        sitres = sitres,
        totger = totger,
        totres = totres,
        totipi = totipi,
        totsub = totsub,
        totdescinc = totdescinc,
        totfrt = totfrt,
        totseg = totseg,
        totoutdesp = totoutdesp,
        vendedorExternalId = vendedorExternalId,
        atendenteCod = atendenteCod,
        dataEntregaPrevista = dataEntregaPrevista,
        descontoComercial = descontoComercial,
        descontoRegional = descontoRegional,
        codigoTransportadora = codigoTransportadora,
        linhaReserva = linhaReserva,
        pedidoAnterior = pedidoAnterior,
        regimeTributario = regimeTributario,
        nomeRegimeTributario = nomeRegimeTributario,
        itens = itens,
        updatedAt = now,
    )
}
