package br.com.vertice.emerion_dashboard.domain.customerorder.model

import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate

/**
 * Domain model for a customer order (header + line items). Plain Kotlin, no
 * JPA/Jakarta/OpenAPI annotations — this is what use cases and ports
 * operate on.
 */
data class CustomerOrder(
    val id: Long?,
    val externalId: String,
    val codigoEmpresa: Int,
    val codigoCliente: Int,
    val cpfCnpj: String?,
    val numeroPedido: String,
    val dataPedido: LocalDate,
    val statusPedido: String?,
    val totalPedidoComImpostos: BigDecimal,
    val totalPedidoSemImpostos: BigDecimal,
    val totalIpi: BigDecimal,
    val totalIcms: BigDecimal,
    val totalPis: BigDecimal,
    val totalCofins: BigDecimal,
    val totalSubstituicaoTributaria: BigDecimal,
    val totalDescontoIncondicional: BigDecimal,
    val totalFrete: BigDecimal? = null,
    val totalSeguro: BigDecimal? = null,
    val totalOutrasDespesas: BigDecimal? = null,
    val vendedorExternalId: Long? = null,
    val dataEntregaPrevista: LocalDate? = null,
    val codigoTransportadora: String? = null,
    val pedidoAnterior: String? = null,
    val regimeTributario: String? = null,
    val nomeRegimeTributario: String? = null,
    val codigoPadraoFaturamento: String? = null,
    val itens: List<CustomerOrderItem>,
    val createdAt: Instant,
    val updatedAt: Instant,
) {
    companion object {
        /** Factory for a brand-new order coming from ingestion (no id yet). */
        fun newFromIngestion(
            externalId: String,
            codigoEmpresa: Int,
            codigoCliente: Int,
            cpfCnpj: String?,
            numeroPedido: String,
            dataPedido: LocalDate,
            statusPedido: String?,
            totalPedidoComImpostos: BigDecimal,
            totalPedidoSemImpostos: BigDecimal,
            totalIpi: BigDecimal,
            totalIcms: BigDecimal,
            totalPis: BigDecimal,
            totalCofins: BigDecimal,
            totalSubstituicaoTributaria: BigDecimal,
            totalDescontoIncondicional: BigDecimal,
            totalFrete: BigDecimal? = null,
            totalSeguro: BigDecimal? = null,
            totalOutrasDespesas: BigDecimal? = null,
            vendedorExternalId: Long? = null,
            dataEntregaPrevista: LocalDate? = null,
            codigoTransportadora: String? = null,
            pedidoAnterior: String? = null,
            regimeTributario: String? = null,
            nomeRegimeTributario: String? = null,
            codigoPadraoFaturamento: String? = null,
            itens: List<CustomerOrderItem>,
            now: Instant,
        ) = CustomerOrder(
            id = null,
            externalId = externalId,
            codigoEmpresa = codigoEmpresa,
            codigoCliente = codigoCliente,
            cpfCnpj = cpfCnpj,
            numeroPedido = numeroPedido,
            dataPedido = dataPedido,
            statusPedido = statusPedido,
            totalPedidoComImpostos = totalPedidoComImpostos,
            totalPedidoSemImpostos = totalPedidoSemImpostos,
            totalIpi = totalIpi,
            totalIcms = totalIcms,
            totalPis = totalPis,
            totalCofins = totalCofins,
            totalSubstituicaoTributaria = totalSubstituicaoTributaria,
            totalDescontoIncondicional = totalDescontoIncondicional,
            totalFrete = totalFrete,
            totalSeguro = totalSeguro,
            totalOutrasDespesas = totalOutrasDespesas,
            vendedorExternalId = vendedorExternalId,
            dataEntregaPrevista = dataEntregaPrevista,
            codigoTransportadora = codigoTransportadora,
            pedidoAnterior = pedidoAnterior,
            regimeTributario = regimeTributario,
            nomeRegimeTributario = nomeRegimeTributario,
            codigoPadraoFaturamento = codigoPadraoFaturamento,
            itens = itens,
            createdAt = now,
            updatedAt = now,
        )
    }

    /**
     * Applies an ingestion update on top of an existing order, bumping
     * updatedAt. The `itens` list is replaced wholesale, matching the
     * source system's contract of always sending the order's complete line
     * items in a single payload.
     */
    fun mergeFromIngestion(
        codigoEmpresa: Int,
        codigoCliente: Int,
        cpfCnpj: String?,
        numeroPedido: String,
        dataPedido: LocalDate,
        statusPedido: String?,
        totalPedidoComImpostos: BigDecimal,
        totalPedidoSemImpostos: BigDecimal,
        totalIpi: BigDecimal,
        totalIcms: BigDecimal,
        totalPis: BigDecimal,
        totalCofins: BigDecimal,
        totalSubstituicaoTributaria: BigDecimal,
        totalDescontoIncondicional: BigDecimal,
        totalFrete: BigDecimal? = null,
        totalSeguro: BigDecimal? = null,
        totalOutrasDespesas: BigDecimal? = null,
        vendedorExternalId: Long? = null,
        dataEntregaPrevista: LocalDate? = null,
        codigoTransportadora: String? = null,
        pedidoAnterior: String? = null,
        regimeTributario: String? = null,
        nomeRegimeTributario: String? = null,
        codigoPadraoFaturamento: String? = null,
        itens: List<CustomerOrderItem>,
        now: Instant,
    ) = copy(
        codigoEmpresa = codigoEmpresa,
        codigoCliente = codigoCliente,
        cpfCnpj = cpfCnpj,
        numeroPedido = numeroPedido,
        dataPedido = dataPedido,
        statusPedido = statusPedido,
        totalPedidoComImpostos = totalPedidoComImpostos,
        totalPedidoSemImpostos = totalPedidoSemImpostos,
        totalIpi = totalIpi,
        totalIcms = totalIcms,
        totalPis = totalPis,
        totalCofins = totalCofins,
        totalSubstituicaoTributaria = totalSubstituicaoTributaria,
        totalDescontoIncondicional = totalDescontoIncondicional,
        totalFrete = totalFrete,
        totalSeguro = totalSeguro,
        totalOutrasDespesas = totalOutrasDespesas,
        vendedorExternalId = vendedorExternalId,
        dataEntregaPrevista = dataEntregaPrevista,
        codigoTransportadora = codigoTransportadora,
        pedidoAnterior = pedidoAnterior,
        regimeTributario = regimeTributario,
        nomeRegimeTributario = nomeRegimeTributario,
        codigoPadraoFaturamento = codigoPadraoFaturamento,
        itens = itens,
        updatedAt = now,
    )
}
