package br.com.vertice.emerion_dashboard.domain.ipi.model

import java.math.BigDecimal
import java.time.Instant

data class Ipi(
    val id: Long?,
    val cnpjEmpresa: String,
    val codigoIpi: String,
    val flgAtivo: String? = null,
    val tipoIpi: String? = null,
    val nomeIpi: String? = null,
    val ncmIpi: String? = null,
    val codigoEnquadramentoLegal: String? = null,
    val cstIpi: String? = null,
    val descricaoSituacaoTributariaIpi: String? = null,
    val aliquotaIpi: BigDecimal? = null,
    val percentualBaseCalculoIpi: BigDecimal? = null,
    val flgSineif20: String? = null,
    val codigoTextoFiscal: String? = null,
    val cstPis: String? = null,
    val descricaoSituacaoTributariaPis: String? = null,
    val aliquotaPis: BigDecimal? = null,
    val incluiDescontoSuframaPis: String? = null,
    val cstCofins: String? = null,
    val descricaoSituacaoTributariaCofins: String? = null,
    val aliquotaCofins: BigDecimal? = null,
    val incluiDescontoSuframaCofins: String? = null,
    val createdAt: Instant,
    val updatedAt: Instant,
) {
    companion object {
        fun newFromIngestion(
            cnpjEmpresa: String,
            codigoIpi: String,
            flgAtivo: String? = null,
            tipoIpi: String? = null,
            nomeIpi: String? = null,
            ncmIpi: String? = null,
            codigoEnquadramentoLegal: String? = null,
            cstIpi: String? = null,
            descricaoSituacaoTributariaIpi: String? = null,
            aliquotaIpi: BigDecimal? = null,
            percentualBaseCalculoIpi: BigDecimal? = null,
            flgSineif20: String? = null,
            codigoTextoFiscal: String? = null,
            cstPis: String? = null,
            descricaoSituacaoTributariaPis: String? = null,
            aliquotaPis: BigDecimal? = null,
            incluiDescontoSuframaPis: String? = null,
            cstCofins: String? = null,
            descricaoSituacaoTributariaCofins: String? = null,
            aliquotaCofins: BigDecimal? = null,
            incluiDescontoSuframaCofins: String? = null,
            now: Instant,
        ) = Ipi(
            id = null,
            cnpjEmpresa = cnpjEmpresa,
            codigoIpi = codigoIpi,
            flgAtivo = flgAtivo,
            tipoIpi = tipoIpi,
            nomeIpi = nomeIpi,
            ncmIpi = ncmIpi,
            codigoEnquadramentoLegal = codigoEnquadramentoLegal,
            cstIpi = cstIpi,
            descricaoSituacaoTributariaIpi = descricaoSituacaoTributariaIpi,
            aliquotaIpi = aliquotaIpi,
            percentualBaseCalculoIpi = percentualBaseCalculoIpi,
            flgSineif20 = flgSineif20,
            codigoTextoFiscal = codigoTextoFiscal,
            cstPis = cstPis,
            descricaoSituacaoTributariaPis = descricaoSituacaoTributariaPis,
            aliquotaPis = aliquotaPis,
            incluiDescontoSuframaPis = incluiDescontoSuframaPis,
            cstCofins = cstCofins,
            descricaoSituacaoTributariaCofins = descricaoSituacaoTributariaCofins,
            aliquotaCofins = aliquotaCofins,
            incluiDescontoSuframaCofins = incluiDescontoSuframaCofins,
            createdAt = now,
            updatedAt = now,
        )
    }

    fun mergeFromIngestion(
        flgAtivo: String? = null,
        tipoIpi: String? = null,
        nomeIpi: String? = null,
        ncmIpi: String? = null,
        codigoEnquadramentoLegal: String? = null,
        cstIpi: String? = null,
        descricaoSituacaoTributariaIpi: String? = null,
        aliquotaIpi: BigDecimal? = null,
        percentualBaseCalculoIpi: BigDecimal? = null,
        flgSineif20: String? = null,
        codigoTextoFiscal: String? = null,
        cstPis: String? = null,
        descricaoSituacaoTributariaPis: String? = null,
        aliquotaPis: BigDecimal? = null,
        incluiDescontoSuframaPis: String? = null,
        cstCofins: String? = null,
        descricaoSituacaoTributariaCofins: String? = null,
        aliquotaCofins: BigDecimal? = null,
        incluiDescontoSuframaCofins: String? = null,
        now: Instant,
    ) = copy(
        flgAtivo = flgAtivo,
        tipoIpi = tipoIpi,
        nomeIpi = nomeIpi,
        ncmIpi = ncmIpi,
        codigoEnquadramentoLegal = codigoEnquadramentoLegal,
        cstIpi = cstIpi,
        descricaoSituacaoTributariaIpi = descricaoSituacaoTributariaIpi,
        aliquotaIpi = aliquotaIpi,
        percentualBaseCalculoIpi = percentualBaseCalculoIpi,
        flgSineif20 = flgSineif20,
        codigoTextoFiscal = codigoTextoFiscal,
        cstPis = cstPis,
        descricaoSituacaoTributariaPis = descricaoSituacaoTributariaPis,
        aliquotaPis = aliquotaPis,
        incluiDescontoSuframaPis = incluiDescontoSuframaPis,
        cstCofins = cstCofins,
        descricaoSituacaoTributariaCofins = descricaoSituacaoTributariaCofins,
        aliquotaCofins = aliquotaCofins,
        incluiDescontoSuframaCofins = incluiDescontoSuframaCofins,
        updatedAt = now,
    )
}
