CREATE TABLE cognito_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub VARCHAR(64) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_cognito_user_sub UNIQUE (sub)
);

CREATE TABLE cognito_user_group (
    cognito_user_id BIGINT NOT NULL REFERENCES cognito_user (id) ON DELETE CASCADE,
    group_name VARCHAR(128) NOT NULL,
    CONSTRAINT pk_cognito_user_group PRIMARY KEY (cognito_user_id, group_name)
);

CREATE INDEX idx_cognito_user_username ON cognito_user (LOWER(username));
CREATE INDEX idx_cognito_user_group_name ON cognito_user_group (group_name);
