CREATE TABLE api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_value VARCHAR(255) NOT NULL UNIQUE,
    server_name VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ
);

CREATE INDEX idx_api_key_value ON api_key (key_value);
CREATE INDEX idx_api_key_server_name ON api_key (server_name);
CREATE INDEX idx_api_key_enabled ON api_key (enabled);
