ALTER TABLE product
    ADD COLUMN unidade_entrada VARCHAR(16),
    ADD COLUMN unidade_saida VARCHAR(16),
    ADD COLUMN desconto_padrao NUMERIC(19, 4),
    ADD COLUMN estoque_disponivel NUMERIC(19, 4),
    ADD COLUMN estoque_minimo NUMERIC(19, 4),
    ADD COLUMN estoque_maximo NUMERIC(19, 4),
    ADD COLUMN estoque_reservado NUMERIC(19, 4),
    ADD COLUMN estoque_adquirido NUMERIC(19, 4),
    ADD COLUMN estoque_atual NUMERIC(19, 4),
    ADD COLUMN estoque_rma NUMERIC(19, 4),
    ADD COLUMN similar_product VARCHAR(255),
    ADD COLUMN quantidade_volumes NUMERIC(19, 4),
    ADD COLUMN quantidade_embalagem NUMERIC(19, 4),
    ADD COLUMN localizacao VARCHAR(255),
    ADD COLUMN cubagem NUMERIC(19, 4),
    ADD COLUMN codigo_barras_embalagem VARCHAR(64),
    ADD COLUMN ibs_c_class_trib VARCHAR(64),
    ADD COLUMN ibs_cst VARCHAR(64),
    ADD COLUMN fcp_entrada NUMERIC(19, 4),
    ADD COLUMN fcp_saida NUMERIC(19, 4),
    ADD COLUMN ipi_saida VARCHAR(64),
    ADD COLUMN ipi_entrada VARCHAR(64),
    ADD COLUMN icm_saida VARCHAR(64),
    ADD COLUMN icm_entrada VARCHAR(64),
    ADD COLUMN icm_st_saida VARCHAR(64),
    ADD COLUMN icm_st_entrada VARCHAR(64),
    ADD COLUMN observacao TEXT;
