CREATE TABLE icms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_empresa VARCHAR(20) NOT NULL,
    codigo_icms VARCHAR(64) NOT NULL,
    tipo_icms VARCHAR(255),
    nome_icms VARCHAR(255),
    uf_emitente VARCHAR(2),
    codigo_regime_tributario VARCHAR(64),
    aliquota_icms NUMERIC(19, 4),
    percentual_reducao_valor_imposto NUMERIC(19, 4),
    percentual_base_calculo_icms NUMERIC(19, 4),
    situacao_tributaria_icms VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_icms_cnpj_empresa_codigo_icms UNIQUE (cnpj_empresa, codigo_icms)
);

CREATE INDEX idx_icms_cnpj_empresa_codigo_icms ON icms (cnpj_empresa, codigo_icms);
