CREATE SCHEMA IF NOT EXISTS emerion_dashboard;

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    nome_fantasia VARCHAR(255) NOT NULL,
    razao_social VARCHAR(255) NOT NULL,
    cpf_cnpj VARCHAR(20) NOT NULL,
    inscricao_estadual VARCHAR(32),
    regime_tributario VARCHAR(64),
    bloqueado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cnpj_empresa VARCHAR(20) NOT NULL,
    data_nascimento DATE,
    data_cadastro DATE,
    data_ultima_atualizacao DATE,
    email1 VARCHAR(255),
    email2 VARCHAR(255),
    website VARCHAR(255),
    limite_credito NUMERIC(19, 4),
    observacoes TEXT,
    cnae VARCHAR(32),
    vendedor_external_id BIGINT,
    nome_vendedor VARCHAR(255),
    codigo_tipo_cliente VARCHAR(64),
    codigo_grupo_cliente VARCHAR(64),
    codigo_categoria_cliente VARCHAR(64),
    uf VARCHAR(2),
    macro_regiao VARCHAR(128),
    micro_regiao VARCHAR(128),
    setor VARCHAR(128),
    CONSTRAINT uk_customer_external_id UNIQUE (external_id)
);

CREATE INDEX idx_customer_nome_fantasia ON customer (LOWER(nome_fantasia));
CREATE INDEX idx_customer_razao_social ON customer (LOWER(razao_social));
CREATE INDEX idx_customer_cpf_cnpj ON customer (cpf_cnpj);
CREATE INDEX idx_customer_bloqueado ON customer (bloqueado);
CREATE INDEX idx_customer_cnpj_empresa ON customer (cnpj_empresa);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    preco NUMERIC(19, 4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cnpj_empresa VARCHAR(20) NOT NULL,
    descricao_reduzida VARCHAR(255),
    referencia_interna VARCHAR(255),
    ncm VARCHAR(32),
    cest VARCHAR(32),
    origem_produto VARCHAR(64),
    categoria VARCHAR(128),
    tipo VARCHAR(128),
    marca VARCHAR(128),
    unidade VARCHAR(16),
    peso_liquido NUMERIC(19, 4),
    peso_bruto NUMERIC(19, 4),
    descontinuado BOOLEAN,
    codigo_barras VARCHAR(64),
    codigo_barras_proprio VARCHAR(64),
    preco2 NUMERIC(19, 4),
    preco3 NUMERIC(19, 4),
    preco4 NUMERIC(19, 4),
    preco5 NUMERIC(19, 4),
    unidade_entrada VARCHAR(16),
    unidade_saida VARCHAR(16),
    desconto_padrao NUMERIC(19, 4),
    estoque_disponivel NUMERIC(19, 4),
    estoque_minimo NUMERIC(19, 4),
    estoque_maximo NUMERIC(19, 4),
    estoque_reservado NUMERIC(19, 4),
    estoque_adquirido NUMERIC(19, 4),
    estoque_atual NUMERIC(19, 4),
    estoque_rma NUMERIC(19, 4),
    similar_product VARCHAR(255),
    quantidade_volumes NUMERIC(19, 4),
    quantidade_embalagem NUMERIC(19, 4),
    localizacao VARCHAR(255),
    cubagem NUMERIC(19, 4),
    codigo_barras_embalagem VARCHAR(64),
    ibs_c_class_trib VARCHAR(64),
    ibs_cst VARCHAR(64),
    fcp_entrada NUMERIC(19, 4),
    fcp_saida NUMERIC(19, 4),
    ipi_saida VARCHAR(64),
    ipi_entrada VARCHAR(64),
    icm_saida VARCHAR(64),
    icm_entrada VARCHAR(64),
    icm_st_saida VARCHAR(64),
    icm_st_entrada VARCHAR(64),
    observacao TEXT,
    CONSTRAINT uk_product_external_id UNIQUE (external_id)
);

CREATE INDEX idx_product_nome ON product (LOWER(nome));
CREATE INDEX idx_product_cnpj_empresa ON product (cnpj_empresa);

CREATE TABLE customer_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    cnpj_empresa VARCHAR(20) NOT NULL,
    cpf_cnpj VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_customer_address_external_id UNIQUE (external_id)
);

CREATE INDEX idx_customer_address_cnpj_empresa ON customer_address (cnpj_empresa);

CREATE TABLE customer_address_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_address_id BIGINT NOT NULL REFERENCES customer_address (id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL,
    cep VARCHAR(16),
    endereco VARCHAR(255),
    numero VARCHAR(16),
    referencia VARCHAR(255),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf VARCHAR(2),
    telefone VARCHAR(32),
    telefone_contato VARCHAR(64),
    complemento VARCHAR(255),
    fax VARCHAR(32),
    tipo_endereco VARCHAR(32),
    ddd_telefone VARCHAR(8),
    ddd_fax VARCHAR(8),
    ddd_celular VARCHAR(8),
    celular VARCHAR(32),
    CONSTRAINT uk_customer_address_detail_tipo UNIQUE (customer_address_id, tipo)
);

CREATE INDEX idx_customer_address_detail_customer_address_id ON customer_address_detail (customer_address_id);

CREATE TABLE customer_credit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_external_id VARCHAR(64) NOT NULL,
    sequencia VARCHAR(32),
    data DATE NOT NULL,
    data_pedido DATE,
    valor_utilizado NUMERIC(19, 4) NOT NULL DEFAULT 0,
    valor_total NUMERIC(19, 4) NOT NULL DEFAULT 0,
    saldo NUMERIC(19, 4) NOT NULL DEFAULT 0,
    situacao VARCHAR(32),
    tipo VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cnpj_empresa VARCHAR(20) NOT NULL,
    CONSTRAINT uk_customer_credit_customer_sequencia UNIQUE (customer_external_id, sequencia, data)
);

CREATE INDEX idx_customer_credit_customer_external_id ON customer_credit (customer_external_id);
CREATE INDEX idx_customer_credit_cnpj_empresa ON customer_credit (cnpj_empresa);

CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    codigo_cliente INTEGER NOT NULL,
    numero_pedido VARCHAR(32),
    data_pedido DATE NOT NULL,
    status_pedido VARCHAR(32),
    total_pedido_com_impostos NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total_pedido_sem_impostos NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total_ipi NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total_substituicao_tributaria NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total_desconto_incondicional NUMERIC(19, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cpf_cnpj VARCHAR(20),
    total_frete NUMERIC(19, 4),
    total_seguro NUMERIC(19, 4),
    total_outras_despesas NUMERIC(19, 4),
    vendedor_external_id BIGINT,
    atendente_cod VARCHAR(64),
    data_entrega_prevista DATE,
    desconto_comercial NUMERIC(19, 4),
    desconto_regional NUMERIC(19, 4),
    codigo_transportadora VARCHAR(64),
    linha_reserva VARCHAR(64),
    pedido_anterior VARCHAR(64),
    regime_tributario VARCHAR(64),
    nome_regime_tributario VARCHAR(128),
    codigo_empresa INTEGER NOT NULL DEFAULT 0,
    total_icms NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total_pis NUMERIC(19, 4) NOT NULL DEFAULT 0,
    total_cofins NUMERIC(19, 4) NOT NULL DEFAULT 0,
    codigo_padrao_faturamento VARCHAR(32),
    CONSTRAINT uk_customer_order_external_id UNIQUE (external_id)
);

CREATE INDEX idx_customer_order_cod_cli ON customer_order (codigo_cliente);
CREATE INDEX idx_customer_order_codigo_cliente ON customer_order (codigo_cliente);
CREATE INDEX idx_customer_order_status_pedido ON customer_order (status_pedido);
CREATE INDEX idx_customer_order_codigo_empresa ON customer_order (codigo_empresa);

CREATE TABLE customer_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id BIGINT NOT NULL REFERENCES customer_order (id) ON DELETE CASCADE,
    produto VARCHAR(64) NOT NULL,
    descricao VARCHAR(255),
    quantidade NUMERIC(19, 4) NOT NULL DEFAULT 0,
    valor_unitario NUMERIC(19, 4) NOT NULL DEFAULT 0,
    valor_total NUMERIC(19, 4) NOT NULL DEFAULT 0,
    seq_re2 INTEGER NOT NULL,
    cod_clp VARCHAR(64),
    cod_st1 VARCHAR(32),
    cod_und VARCHAR(16),
    vlu_re2 NUMERIC(19, 4),
    dsc_re2 NUMERIC(19, 4),
    dsr_re2 NUMERIC(19, 4),
    icms_aliquota NUMERIC(19, 4),
    icms_base NUMERIC(19, 4),
    icms_valor NUMERIC(19, 4),
    icms_reducao_base NUMERIC(19, 4),
    icms_substituicao_base NUMERIC(19, 4),
    icms_substituicao_valor NUMERIC(19, 4),
    icms_substituicao_aliquota NUMERIC(19, 4),
    icms_substituicao_margem NUMERIC(19, 4),
    icms_substituicao_reducao_base NUMERIC(19, 4),
    ipi_aliquota NUMERIC(19, 4),
    ipi_base NUMERIC(19, 4),
    ipi_valor NUMERIC(19, 4),
    ipi_classificacao VARCHAR(32),
    ipi_cst VARCHAR(8),
    pis_base NUMERIC(19, 4),
    pis_aliquota NUMERIC(19, 4),
    pis_valor NUMERIC(19, 4),
    pis_cst VARCHAR(8),
    cofins_base NUMERIC(19, 4),
    cofins_aliquota NUMERIC(19, 4),
    cofins_valor NUMERIC(19, 4),
    cofins_cst VARCHAR(8),
    desconto_valor NUMERIC(19, 4),
    frete_valor NUMERIC(19, 4),
    seguro_valor NUMERIC(19, 4),
    outras_despesas_valor NUMERIC(19, 4),
    total_item_tributado NUMERIC(19, 4),
    tot_ren NUMERIC(19, 4),
    tot_ge2 NUMERIC(19, 4),
    observacao VARCHAR(500),
    pedido_compra_cliente VARCHAR(64),
    item_pedido_compra_cliente INTEGER,
    nro_re2 INTEGER,
    flg_val VARCHAR(4),
    flg_pac VARCHAR(4),
    flg_lib VARCHAR(4),
    cod_cfo VARCHAR(16),
    codcor VARCHAR(32),
    codtam VARCHAR(32),
    descricao_nfe VARCHAR(255),
    peso_liquido NUMERIC(19, 4),
    peso_bruto NUMERIC(19, 4),
    referencia VARCHAR(128),
    quantidade_faturada NUMERIC(19, 4),
    quantidade_separada NUMERIC(19, 4),
    cod_emp INTEGER NOT NULL DEFAULT 0,
    dteres DATE NOT NULL DEFAULT CURRENT_DATE,
    numres VARCHAR(64) NOT NULL DEFAULT '',
    custo_total NUMERIC(19, 4),
    lucro_valor NUMERIC(19, 4),
    lucro_porcentagem NUMERIC(19, 4),
    CONSTRAINT uk_customer_order_item_seq_re2 UNIQUE (customer_order_id, seq_re2)
);

CREATE INDEX idx_customer_order_item_customer_order_id ON customer_order_item (customer_order_id);

CREATE TABLE vendedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    apelido VARCHAR(255),
    cpf_cnpj VARCHAR(32),
    telefone VARCHAR(32),
    celular VARCHAR(32),
    email VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(8),
    situacao VARCHAR(32),
    saldo NUMERIC(19, 4),
    data_cadastro DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cnpj_empresa VARCHAR(20) NOT NULL,
    CONSTRAINT uk_vendedor_external_id UNIQUE (external_id)
);

CREATE INDEX idx_vendedor_nome ON vendedor (LOWER(nome));
CREATE INDEX idx_vendedor_situacao ON vendedor (situacao);
CREATE INDEX idx_vendedor_cnpj_empresa ON vendedor (cnpj_empresa);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'UNREAD',
    category VARCHAR(32) NOT NULL,
    priority VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    reference_type VARCHAR(64),
    reference_id VARCHAR(64),
    action_url VARCHAR(2048),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at TIMESTAMPTZ,
    dismissed_at TIMESTAMPTZ
);

CREATE INDEX idx_notification_user_id ON notification (user_id);
CREATE INDEX idx_notification_user_id_status ON notification (user_id, status);
CREATE INDEX idx_notification_category ON notification (category);

CREATE TABLE cognito_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub VARCHAR(64) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_cognito_user_sub UNIQUE (sub)
);

CREATE TABLE cognito_user_group (
    cognito_user_id BIGINT NOT NULL REFERENCES cognito_user (id) ON DELETE CASCADE,
    group_name VARCHAR(128) NOT NULL,
    CONSTRAINT pk_cognito_user_group PRIMARY KEY (cognito_user_id, group_name)
);

CREATE INDEX idx_cognito_user_username ON cognito_user (LOWER(username));
CREATE INDEX idx_cognito_user_group_name ON cognito_user_group (group_name);

CREATE TABLE api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_value VARCHAR(255) NOT NULL UNIQUE,
    server_name VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ
);

CREATE INDEX idx_api_key_value ON api_key (key_value);
CREATE INDEX idx_api_key_server_name ON api_key (server_name);
CREATE INDEX idx_api_key_enabled ON api_key (enabled);

CREATE TABLE icms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_empresa VARCHAR(20) NOT NULL,
    codigo_icms VARCHAR(64) NOT NULL,
    tipo_icms VARCHAR(255),
    nome_icms VARCHAR(255),
    uf_emitente VARCHAR(2),
    codigo_regime_tributario VARCHAR(64),
    aliquota_icms NUMERIC(19, 4),
    percentual_reducao_valor_imposto NUMERIC(19, 4),
    percentual_base_calculo_icms NUMERIC(19, 4),
    situacao_tributaria_icms VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_icms_cnpj_empresa_codigo_icms UNIQUE (cnpj_empresa, codigo_icms)
);

CREATE INDEX idx_icms_cnpj_empresa_codigo_icms ON icms (cnpj_empresa, codigo_icms);

CREATE TABLE ipi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_empresa VARCHAR(20) NOT NULL,
    codigo_ipi VARCHAR(64) NOT NULL,
    flg_ativo VARCHAR(8),
    tipo_ipi VARCHAR(32),
    nome_ipi VARCHAR(255),
    ncm_ipi VARCHAR(16),
    codigo_enquadramento_legal VARCHAR(64),
    cst_ipi VARCHAR(8),
    descricao_situacao_tributaria_ipi VARCHAR(255),
    aliquota_ipi NUMERIC(19, 4),
    percentual_base_calculo_ipi NUMERIC(19, 4),
    flg_sineif20 VARCHAR(8),
    codigo_texto_fiscal VARCHAR(64),
    cst_pis VARCHAR(8),
    descricao_situacao_tributaria_pis VARCHAR(255),
    aliquota_pis NUMERIC(19, 4),
    inclui_desconto_suframa_pis VARCHAR(8),
    cst_cofins VARCHAR(8),
    descricao_situacao_tributaria_cofins VARCHAR(255),
    aliquota_cofins NUMERIC(19, 4),
    inclui_desconto_suframa_cofins VARCHAR(8),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_ipi_cnpj_empresa_codigo_ipi UNIQUE (cnpj_empresa, codigo_ipi)
);

CREATE INDEX idx_ipi_cnpj_empresa_codigo_ipi ON ipi (cnpj_empresa, codigo_ipi);

CREATE TABLE titulo_receber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_empresa VARCHAR(20) NOT NULL,
    codigo_empresa BIGINT,
    data_emissao DATE,
    documento VARCHAR(64) NOT NULL,
    codigo_condicao_recebimento VARCHAR(64),
    nome_condicao_recebimento VARCHAR(255),
    nome_empresa VARCHAR(255),
    codigo_comissao BIGINT,
    percentual_comissao NUMERIC(19, 4),
    codigo_cliente BIGINT,
    nome_cliente VARCHAR(255),
    codigo_vendedor BIGINT,
    nome_vendedor VARCHAR(255),
    codigo_tipo_documento VARCHAR(64),
    nome_tipo_documento VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_titulo_receber_documento UNIQUE (documento),
    CONSTRAINT uk_titulo_receber_cnpj_documento UNIQUE (cnpj_empresa, documento)
);

CREATE INDEX idx_titulo_receber_cnpj_documento ON titulo_receber (cnpj_empresa, documento);

CREATE TABLE titulo_receber_parcela (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(64) NOT NULL REFERENCES titulo_receber (documento) ON DELETE CASCADE,
    numero_parcela INTEGER NOT NULL,
    flag_incobravel VARCHAR(32),
    data_incobravel DATE,
    data_vencimento DATE,
    prazo_em_dias INTEGER,
    valor_parcela NUMERIC(19, 4),
    numero_bancario VARCHAR(64),
    codigo_banco VARCHAR(32),
    nome_banco VARCHAR(255),
    observacoes TEXT,
    flag_carta_anuencia VARCHAR(32),
    data_carta_anuencia DATE,
    flag_pago VARCHAR(8),
    CONSTRAINT uk_titulo_receber_parcela_documento_numero UNIQUE (documento, numero_parcela)
);

CREATE INDEX idx_titulo_receber_parcela_documento ON titulo_receber_parcela (documento);

CREATE TABLE liberacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_empresa VARCHAR(20) NOT NULL,
    codigo_empresa BIGINT NOT NULL,
    data_pedido DATE NOT NULL,
    numero_pedido VARCHAR(64) NOT NULL,
    numero_liberacao INTEGER NOT NULL,
    data_liberacao DATE NOT NULL,
    hora_liberacao TIME NOT NULL,
    codigo_cliente BIGINT NOT NULL,
    quantidade_separada NUMERIC(19, 4) NOT NULL,
    total_liberado_sem_impostos NUMERIC(19, 4) NOT NULL,
    total_liberado_com_impostos NUMERIC(19, 4) NOT NULL,
    situacao_liberacao VARCHAR(64) NOT NULL,
    codigo_vendedor BIGINT NOT NULL,
    comissao_liberacao NUMERIC(19, 4) NOT NULL,
    total_custo NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_liberacao_pedido_numero UNIQUE (numero_pedido, numero_liberacao)
);

CREATE INDEX idx_liberacao_cnpj_empresa ON liberacao (cnpj_empresa);

CREATE TABLE liberacao_detalhe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(64) NOT NULL,
    numero_liberacao INTEGER NOT NULL,
    numero_sequencia_liberacao INTEGER NOT NULL,
    classificacao_item VARCHAR(64) NOT NULL,
    codigo_grupo VARCHAR(64) NOT NULL,
    codigo_sub_grupo VARCHAR(64) NOT NULL,
    codigo_produto VARCHAR(64) NOT NULL,
    descricao_item_liberacao TEXT NOT NULL,
    quantidade_no_pedido NUMERIC(19, 4) NOT NULL,
    total_separado NUMERIC(19, 4) NOT NULL,
    quantidade_restante NUMERIC(19, 4) NOT NULL,
    total_valor_liquido NUMERIC(19, 4) NOT NULL,
    total_valor_bruto NUMERIC(19, 4) NOT NULL,
    percentual_desconto NUMERIC(19, 4) NOT NULL,
    total_custo NUMERIC(19, 4) NOT NULL,
    percentual_de_acrescimo NUMERIC(19, 4) NOT NULL,
    preco_venda_item NUMERIC(19, 4) NOT NULL,
    preco_praticado NUMERIC(19, 4) NOT NULL,
    custo_praticado NUMERIC(19, 4) NOT NULL,
    CONSTRAINT fk_liberacao_detalhe_liberacao
        FOREIGN KEY (numero_pedido, numero_liberacao)
            REFERENCES liberacao (numero_pedido, numero_liberacao)
            ON DELETE CASCADE,
    CONSTRAINT uk_liberacao_detalhe_sequencia
        UNIQUE (numero_pedido, numero_liberacao, numero_sequencia_liberacao)
);

CREATE INDEX idx_liberacao_detalhe_liberacao
    ON liberacao_detalhe (numero_pedido, numero_liberacao);
