CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    nome_fantasia VARCHAR(255) NOT NULL,
    razao_social VARCHAR(255) NOT NULL,
    cpf_cnpj VARCHAR(20) NOT NULL,
    inscricao_estadual VARCHAR(32),
    regime_tributario VARCHAR(32),
    bloqueado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_customer_external_id UNIQUE (external_id)
);

CREATE INDEX idx_customer_nome_fantasia ON customer (LOWER(nome_fantasia));
CREATE INDEX idx_customer_razao_social ON customer (LOWER(razao_social));
CREATE INDEX idx_customer_cpf_cnpj ON customer (cpf_cnpj);
CREATE INDEX idx_customer_bloqueado ON customer (bloqueado);
