CREATE TABLE ipi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_empresa VARCHAR(20) NOT NULL,
    codigo_ipi VARCHAR(64) NOT NULL,
    flg_ativo VARCHAR(8),
    tipo_ipi VARCHAR(32),
    nome_ipi VARCHAR(255),
    ncm_ipi VARCHAR(16),
    codigo_enquadramento_legal VARCHAR(64),
    cst_ipi VARCHAR(8),
    descricao_situacao_tributaria_ipi VARCHAR(255),
    aliquota_ipi NUMERIC(19, 4),
    percentual_base_calculo_ipi NUMERIC(19, 4),
    flg_sineif20 VARCHAR(8),
    codigo_texto_fiscal VARCHAR(64),
    cst_pis VARCHAR(8),
    descricao_situacao_tributaria_pis VARCHAR(255),
    aliquota_pis NUMERIC(19, 4),
    inclui_desconto_suframa_pis VARCHAR(8),
    cst_cofins VARCHAR(8),
    descricao_situacao_tributaria_cofins VARCHAR(255),
    aliquota_cofins NUMERIC(19, 4),
    inclui_desconto_suframa_cofins VARCHAR(8),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_ipi_cnpj_empresa_codigo_ipi UNIQUE (cnpj_empresa, codigo_ipi)
);

CREATE INDEX idx_ipi_cnpj_empresa_codigo_ipi ON ipi (cnpj_empresa, codigo_ipi);
