CREATE TABLE titulo_receber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_empresa VARCHAR(20) NOT NULL,
    codigo_empresa BIGINT,
    data_emissao DATE,
    documento VARCHAR(64) NOT NULL,
    codigo_condicao_recebimento VARCHAR(64),
    nome_condicao_recebimento VARCHAR(255),
    nome_empresa VARCHAR(255),
    codigo_comissao BIGINT,
    percentual_comissao NUMERIC(19, 4),
    codigo_cliente BIGINT,
    nome_cliente VARCHAR(255),
    codigo_vendedor BIGINT,
    nome_vendedor VARCHAR(255),
    codigo_tipo_documento VARCHAR(64),
    nome_tipo_documento VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_titulo_receber_documento UNIQUE (documento),
    CONSTRAINT uk_titulo_receber_cnpj_documento UNIQUE (cnpj_empresa, documento)
);

CREATE INDEX idx_titulo_receber_cnpj_documento ON titulo_receber (cnpj_empresa, documento);

CREATE TABLE titulo_receber_parcela (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(64) NOT NULL REFERENCES titulo_receber (documento) ON DELETE CASCADE,
    numero_parcela INTEGER NOT NULL,
    flag_incobravel VARCHAR(32),
    data_incobravel DATE,
    data_vencimento DATE,
    prazo_em_dias INTEGER,
    valor_parcela NUMERIC(19, 4),
    numero_bancario VARCHAR(64),
    codigo_banco VARCHAR(32),
    nome_banco VARCHAR(255),
    observacoes TEXT,
    flag_carta_anuencia VARCHAR(32),
    data_carta_anuencia DATE,
    flag_pago VARCHAR(8),
    CONSTRAINT uk_titulo_receber_parcela_documento_numero UNIQUE (documento, numero_parcela)
);

CREATE INDEX idx_titulo_receber_parcela_documento ON titulo_receber_parcela (documento);
