
CREATE TABLE liberacao (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cnpj_empresa VARCHAR(20) NOT NULL,
   codigo_empresa BIGINT NOT NULL,
   data_pedido DATE NOT NULL,
   numero_pedido VARCHAR(64) NOT NULL,
   numero_liberacao INTEGER NOT NULL,
   data_liberacao DATE NOT NULL,
   hora_liberacao TIME NOT NULL,
   codigo_cliente BIGINT NOT NULL,
   quantidade_separada NUMERIC(19, 4) NOT NULL,
   total_liberado_sem_impostos NUMERIC(19, 4) NOT NULL,
   total_liberado_com_impostos NUMERIC(19, 4) NOT NULL,
   situacao_liberacao VARCHAR(64) NOT NULL,
   codigo_vendedor BIGINT NOT NULL,
   comissao_liberacao NUMERIC(19, 4) NOT NULL,
   total_custo NUMERIC(19, 4) NOT NULL,
   created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
   updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
   CONSTRAINT uk_liberacao_pedido_numero UNIQUE (numero_pedido, numero_liberacao)
);

CREATE INDEX idx_liberacao_cnpj_empresa ON liberacao (cnpj_empresa);

CREATE TABLE liberacao_detalhe (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   numero_pedido VARCHAR(64) NOT NULL,
   numero_liberacao INTEGER NOT NULL,
   numero_sequencia_liberacao INTEGER NOT NULL,
   classificacao_item VARCHAR(64) NOT NULL,
   codigo_grupo VARCHAR(64) NOT NULL,
   codigo_sub_grupo VARCHAR(64) NOT NULL,
   codigo_produto VARCHAR(64) NOT NULL,
   descricao_item_liberacao TEXT NOT NULL,
   quantidade_no_pedido NUMERIC(19, 4) NOT NULL,
   total_separado NUMERIC(19, 4) NOT NULL,
   quantidade_restante NUMERIC(19, 4) NOT NULL,
   total_valor_liquido NUMERIC(19, 4) NOT NULL,
   total_valor_bruto NUMERIC(19, 4) NOT NULL,
   percentual_desconto NUMERIC(19, 4) NOT NULL,
   total_custo NUMERIC(19, 4) NOT NULL,
   percentual_de_acrescimo NUMERIC(19, 4) NOT NULL,
   preco_venda_item NUMERIC(19, 4) NOT NULL,
   preco_praticado NUMERIC(19, 4) NOT NULL,
   custo_praticado NUMERIC(19, 4) NOT NULL,
   CONSTRAINT fk_liberacao_detalhe_liberacao
       FOREIGN KEY (numero_pedido, numero_liberacao)
           REFERENCES liberacao (numero_pedido, numero_liberacao)
           ON DELETE CASCADE,
   CONSTRAINT uk_liberacao_detalhe_sequencia
       UNIQUE (numero_pedido, numero_liberacao, numero_sequencia_liberacao)
);

CREATE INDEX idx_liberacao_detalhe_liberacao
    ON liberacao_detalhe (numero_pedido, numero_liberacao);
