CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    preco NUMERIC(19, 4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_product_external_id UNIQUE (external_id)
);

CREATE INDEX idx_product_nome ON product (LOWER(nome));
