CREATE TABLE customer_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    cnpj_empresa VARCHAR(20),
    cpf_cnpj VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_customer_address_external_id UNIQUE (external_id)
);

CREATE TABLE customer_address_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_address_id BIGINT NOT NULL REFERENCES customer_address (id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL,
    cep VARCHAR(16),
    endereco VARCHAR(255),
    numero VARCHAR(16),
    referencia VARCHAR(255),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    uf VARCHAR(2),
    telefone VARCHAR(32),
    telefone_contato VARCHAR(64),
    complemento VARCHAR(255),
    fax VARCHAR(32),
    CONSTRAINT uk_customer_address_detail_tipo UNIQUE (customer_address_id, tipo)
);

CREATE INDEX idx_customer_address_detail_customer_address_id ON customer_address_detail (customer_address_id);
