CREATE TABLE customer_credit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_external_id VARCHAR(64) NOT NULL,
    sequencia VARCHAR(32),
    data TIMESTAMPTZ NOT NULL,
    data_pedido TIMESTAMPTZ,
    valor_utilizado NUMERIC(19, 4) NOT NULL DEFAULT 0,
    valor_total NUMERIC(19, 4) NOT NULL DEFAULT 0,
    saldo NUMERIC(19, 4) NOT NULL DEFAULT 0,
    situacao VARCHAR(32),
    tipo VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_customer_credit_customer_sequencia UNIQUE (customer_external_id, sequencia)
);

CREATE INDEX idx_customer_credit_customer_external_id ON customer_credit (customer_external_id);
