CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    cod_cli VARCHAR(64) NOT NULL,
    cnpj_empresa VARCHAR(20),
    nronfe VARCHAR(32),
    dteres TIMESTAMPTZ NOT NULL,
    sitres VARCHAR(32),
    totger NUMERIC(19, 4) NOT NULL DEFAULT 0,
    totres NUMERIC(19, 4) NOT NULL DEFAULT 0,
    totipi NUMERIC(19, 4) NOT NULL DEFAULT 0,
    totsub NUMERIC(19, 4) NOT NULL DEFAULT 0,
    totdescinc NUMERIC(19, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_customer_order_external_id UNIQUE (external_id)
);

CREATE INDEX idx_customer_order_cod_cli ON customer_order (cod_cli);

CREATE TABLE customer_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id BIGINT NOT NULL REFERENCES customer_order (id) ON DELETE CASCADE,
    produto VARCHAR(64) NOT NULL,
    descricao VARCHAR(255),
    quantidade NUMERIC(19, 4) NOT NULL DEFAULT 0,
    valor_unitario NUMERIC(19, 4) NOT NULL DEFAULT 0,
    valor_total NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT uk_customer_order_item_produto UNIQUE (customer_order_id, produto)
);

CREATE INDEX idx_customer_order_item_customer_order_id ON customer_order_item (customer_order_id);
