CREATE TABLE vendedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(64) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    apelido VARCHAR(255),
    cpf_cnpj VARCHAR(32),
    telefone VARCHAR(32),
    celular VARCHAR(32),
    email VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(8),
    situacao VARCHAR(32),
    saldo NUMERIC(19, 4),
    data_cadastro DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_vendedor_external_id UNIQUE (external_id)
);

CREATE INDEX idx_vendedor_nome ON vendedor (LOWER(nome));
CREATE INDEX idx_vendedor_situacao ON vendedor (situacao);
