-- Adds the additional PEDRE2 fields now exposed by emerion-load-service's
-- CustomerOrderItemProjection (tax/fiscal breakdown, discounts, and legacy
-- tracking flags for each order line item). All columns are nullable
-- except seq_re2, which every source row is expected to carry.
ALTER TABLE customer_order_item
    ADD COLUMN seq_re2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN cod_clp VARCHAR(64),
    ADD COLUMN cod_st1 VARCHAR(32),
    ADD COLUMN cod_und VARCHAR(16),
    ADD COLUMN vlu_re2 NUMERIC(19, 4),
    ADD COLUMN dsc_re2 NUMERIC(19, 4),
    ADD COLUMN dsr_re2 NUMERIC(19, 4),
    ADD COLUMN icms_aliquota NUMERIC(19, 4),
    ADD COLUMN icms_base NUMERIC(19, 4),
    ADD COLUMN icms_valor NUMERIC(19, 4),
    ADD COLUMN icms_reducao_base NUMERIC(19, 4),
    ADD COLUMN icms_substituicao_base NUMERIC(19, 4),
    ADD COLUMN icms_substituicao_valor NUMERIC(19, 4),
    ADD COLUMN icms_substituicao_aliquota NUMERIC(19, 4),
    ADD COLUMN icms_substituicao_margem NUMERIC(19, 4),
    ADD COLUMN icms_substituicao_reducao_base NUMERIC(19, 4),
    ADD COLUMN ipi_aliquota NUMERIC(19, 4),
    ADD COLUMN ipi_base NUMERIC(19, 4),
    ADD COLUMN ipi_valor NUMERIC(19, 4),
    ADD COLUMN ipi_classificacao VARCHAR(32),
    ADD COLUMN ipi_cst VARCHAR(8),
    ADD COLUMN pis_base NUMERIC(19, 4),
    ADD COLUMN pis_aliquota NUMERIC(19, 4),
    ADD COLUMN pis_valor NUMERIC(19, 4),
    ADD COLUMN pis_cst VARCHAR(8),
    ADD COLUMN cofins_base NUMERIC(19, 4),
    ADD COLUMN cofins_aliquota NUMERIC(19, 4),
    ADD COLUMN cofins_valor NUMERIC(19, 4),
    ADD COLUMN cofins_cst VARCHAR(8),
    ADD COLUMN desconto_valor NUMERIC(19, 4),
    ADD COLUMN frete_valor NUMERIC(19, 4),
    ADD COLUMN seguro_valor NUMERIC(19, 4),
    ADD COLUMN outras_despesas_valor NUMERIC(19, 4),
    ADD COLUMN total_item_tributado NUMERIC(19, 4),
    ADD COLUMN tot_ren NUMERIC(19, 4),
    ADD COLUMN tot_ge2 NUMERIC(19, 4),
    ADD COLUMN observacao VARCHAR(500),
    ADD COLUMN pedido_compra_cliente VARCHAR(64),
    ADD COLUMN item_pedido_compra_cliente INTEGER,
    ADD COLUMN nro_re2 INTEGER,
    ADD COLUMN flg_val VARCHAR(4),
    ADD COLUMN flg_pac VARCHAR(4),
    ADD COLUMN flg_lib VARCHAR(4),
    ADD COLUMN cod_cfo VARCHAR(16);

ALTER TABLE customer_order_item ALTER COLUMN seq_re2 DROP DEFAULT;
