package br.com.vertice.emerion_dashboard.application.customerorder.ingestion.model

import java.math.BigDecimal

/** Input command for a single line item inside a customer order ingestion item. */
data class IngestCustomerOrderItemCommand(
    val produto: String,
    val descricao: String? = null,
    val quantidade: BigDecimal,
    val valorUnitario: BigDecimal,
    val valorTotal: BigDecimal,
    val seqRe2: Int,
    val codClp: String? = null,
    val codSt1: String? = null,
    val codUnd: String? = null,
    val vluRe2: BigDecimal? = null,
    val dscRe2: BigDecimal? = null,
    val dsrRe2: BigDecimal? = null,
    val icmsAliquota: BigDecimal? = null,
    val icmsBase: BigDecimal? = null,
    val icmsValor: BigDecimal? = null,
    val icmsReducaoBase: BigDecimal? = null,
    val icmsSubstituicaoBase: BigDecimal? = null,
    val icmsSubstituicaoValor: BigDecimal? = null,
    val icmsSubstituicaoAliquota: BigDecimal? = null,
    val icmsSubstituicaoMargem: BigDecimal? = null,
    val icmsSubstituicaoReducaoBase: BigDecimal? = null,
    val ipiAliquota: BigDecimal? = null,
    val ipiBase: BigDecimal? = null,
    val ipiValor: BigDecimal? = null,
    val ipiClassificacao: String? = null,
    val ipiCst: String? = null,
    val pisBase: BigDecimal? = null,
    val pisAliquota: BigDecimal? = null,
    val pisValor: BigDecimal? = null,
    val pisCst: String? = null,
    val cofinsBase: BigDecimal? = null,
    val cofinsAliquota: BigDecimal? = null,
    val cofinsValor: BigDecimal? = null,
    val cofinsCst: String? = null,
    val descontoValor: BigDecimal? = null,
    val freteValor: BigDecimal? = null,
    val seguroValor: BigDecimal? = null,
    val outrasDespesasValor: BigDecimal? = null,
    val totalItemTributado: BigDecimal? = null,
    val totRen: BigDecimal? = null,
    val totGe2: BigDecimal? = null,
    val observacao: String? = null,
    val pedidoCompraCliente: String? = null,
    val itemPedidoCompraCliente: Int? = null,
    val nroRe2: Int? = null,
    val flgVal: String? = null,
    val flgPac: String? = null,
    val flgLib: String? = null,
    val codCfo: String? = null,
)
