package br.com.vertice.emerion_dashboard.adapter.mapper

import br.com.vertice.emerion_dashboard.adapter.outbound.persistence.entity.ProductJpaEntity
import br.com.vertice.emerion_dashboard.adapter.outbound.persistence.projection.ProductProjection
import br.com.vertice.emerion_dashboard.domain.product.Product

/** Maps between the domain model and the JPA entity/read projection. Kept out of the entity/domain classes on purpose. */
object ProductPersistenceMapper {

    /** Read path: native-query projection (see `ProductRepository`) -> domain model. */
    fun ProductProjection.toDomain(): Product =
        Product(
            id = id,
            externalId = externalId,
            cnpjEmpresa = cnpjEmpresa,
            nome = nome,
            descricaoReduzida = descricaoReduzida,
            referenciaInterna = referenciaInterna,
            ncm = ncm,
            cest = cest,
            origemProduto = origemProduto,
            categoria = categoria,
            tipo = tipo,
            marca = marca,
            unidade = unidade,
            unidadeEntrada = unidadeEntrada,
            unidadeSaida = unidadeSaida,
            pesoLiquido = pesoLiquido,
            pesoBruto = pesoBruto,
            descontinuado = descontinuado,
            codigoBarras = codigoBarras,
            codigoBarrasProprio = codigoBarrasProprio,
            preco = preco,
            preco2 = preco2,
            preco3 = preco3,
            preco4 = preco4,
            preco5 = preco5,
            descontoPadrao = descontoPadrao,
            estoqueDisponivel = estoqueDisponivel,
            estoqueMinimo = estoqueMinimo,
            estoqueMaximo = estoqueMaximo,
            estoqueReservado = estoqueReservado,
            estoqueAdquirido = estoqueAdquirido,
            estoqueAtual = estoqueAtual,
            estoqueRma = estoqueRma,
            similar = similarProduct,
            quantidadeVolumes = quantidadeVolumes,
            quantidadeEmbalagem = quantidadeEmbalagem,
            localizacao = localizacao,
            cubagem = cubagem,
            codigoBarrasEmbalagem = codigoBarrasEmbalagem,
            ibsCClassTrib = ibsCClassTrib,
            ibsCst = ibsCst,
            fcpEntrada = fcpEntrada,
            fcpSaida = fcpSaida,
            ipiSaida = ipiSaida,
            ipiEntrada = ipiEntrada,
            icmSaida = icmSaida,
            icmEntrada = icmEntrada,
            icmStSaida = icmStSaida,
            icmStEntrada = icmStEntrada,
            observacao = observacao,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    /** Write path: JPA entity -> domain model. */
    fun ProductJpaEntity.toDomain(): Product =
        Product(
            id = id,
            externalId = externalId,
            cnpjEmpresa = cnpjEmpresa,
            nome = nome,
            descricaoReduzida = descricaoReduzida,
            referenciaInterna = referenciaInterna,
            ncm = ncm,
            cest = cest,
            origemProduto = origemProduto,
            categoria = categoria,
            tipo = tipo,
            marca = marca,
            unidade = unidade,
            unidadeEntrada = unidadeEntrada,
            unidadeSaida = unidadeSaida,
            pesoLiquido = pesoLiquido,
            pesoBruto = pesoBruto,
            descontinuado = descontinuado,
            codigoBarras = codigoBarras,
            codigoBarrasProprio = codigoBarrasProprio,
            preco = preco,
            preco2 = preco2,
            preco3 = preco3,
            preco4 = preco4,
            preco5 = preco5,
            descontoPadrao = descontoPadrao,
            estoqueDisponivel = estoqueDisponivel,
            estoqueMinimo = estoqueMinimo,
            estoqueMaximo = estoqueMaximo,
            estoqueReservado = estoqueReservado,
            estoqueAdquirido = estoqueAdquirido,
            estoqueAtual = estoqueAtual,
            estoqueRma = estoqueRma,
            similar = similar,
            quantidadeVolumes = quantidadeVolumes,
            quantidadeEmbalagem = quantidadeEmbalagem,
            localizacao = localizacao,
            cubagem = cubagem,
            codigoBarrasEmbalagem = codigoBarrasEmbalagem,
            ibsCClassTrib = ibsCClassTrib,
            ibsCst = ibsCst,
            fcpEntrada = fcpEntrada,
            fcpSaida = fcpSaida,
            ipiSaida = ipiSaida,
            ipiEntrada = ipiEntrada,
            icmSaida = icmSaida,
            icmEntrada = icmEntrada,
            icmStSaida = icmStSaida,
            icmStEntrada = icmStEntrada,
            observacao = observacao,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )

    /** Applies domain state onto a (possibly new) JPA entity, preserving the generated id. */
    fun Product.toEntity(existing: ProductJpaEntity?): ProductJpaEntity =
        ProductJpaEntity(
            id = existing?.id ?: id,
            externalId = externalId,
            cnpjEmpresa = cnpjEmpresa,
            nome = nome,
            descricaoReduzida = descricaoReduzida,
            referenciaInterna = referenciaInterna,
            ncm = ncm,
            cest = cest,
            origemProduto = origemProduto,
            categoria = categoria,
            tipo = tipo,
            marca = marca,
            unidade = unidade,
            unidadeEntrada = unidadeEntrada,
            unidadeSaida = unidadeSaida,
            pesoLiquido = pesoLiquido,
            pesoBruto = pesoBruto,
            descontinuado = descontinuado,
            codigoBarras = codigoBarras,
            codigoBarrasProprio = codigoBarrasProprio,
            preco = preco,
            preco2 = preco2,
            preco3 = preco3,
            preco4 = preco4,
            preco5 = preco5,
            custoUltimaCompra = custoUltimaCompra,
            custoPonderado = custoPonderado,
            markup = markup,
            descontoPadrao = descontoPadrao,
            estoqueDisponivel = estoqueDisponivel,
            estoqueMinimo = estoqueMinimo,
            estoqueMaximo = estoqueMaximo,
            estoqueReservado = estoqueReservado,
            estoqueAdquirido = estoqueAdquirido,
            estoqueAtual = estoqueAtual,
            estoqueRma = estoqueRma,
            similar = similar,
            quantidadeVolumes = quantidadeVolumes,
            quantidadeEmbalagem = quantidadeEmbalagem,
            localizacao = localizacao,
            cubagem = cubagem,
            codigoBarrasEmbalagem = codigoBarrasEmbalagem,
            ibsCClassTrib = ibsCClassTrib,
            ibsCst = ibsCst,
            fcpEntrada = fcpEntrada,
            fcpSaida = fcpSaida,
            ipiSaida = ipiSaida,
            ipiEntrada = ipiEntrada,
            icmSaida = icmSaida,
            icmEntrada = icmEntrada,
            icmStSaida = icmStSaida,
            icmStEntrada = icmStEntrada,
            observacao = observacao,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )
}
