package br.com.vertice.emerion_dashboard.domain.fincre.model

import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate

data class Fincre(
    val id: Long?,
    val cnpjEmpresa: String,
    val codigoEmpresa: Long? = null,
    val dataEmissao: LocalDate? = null,
    val documento: String,
    val codigoCondicaoRecebimento: String? = null,
    val nomeCondicaoRecebimento: String? = null,
    val nomeEmpresa: String? = null,
    val codigoComissao: Long? = null,
    val percentualComissao: BigDecimal? = null,
    val codigoCliente: Long? = null,
    val nomeCliente: String? = null,
    val codigoVendedor: Long? = null,
    val nomeVendedor: String? = null,
    val codigoTipoDocumento: String? = null,
    val nomeTipoDocumento: String? = null,
    val parcelas: List<FincreParcela>,
    val createdAt: Instant,
    val updatedAt: Instant,
) {
    companion object {
        fun newFromIngestion(
            cnpjEmpresa: String,
            codigoEmpresa: Long? = null,
            dataEmissao: LocalDate? = null,
            documento: String,
            codigoCondicaoRecebimento: String? = null,
            nomeCondicaoRecebimento: String? = null,
            nomeEmpresa: String? = null,
            codigoComissao: Long? = null,
            percentualComissao: BigDecimal? = null,
            codigoCliente: Long? = null,
            nomeCliente: String? = null,
            codigoVendedor: Long? = null,
            nomeVendedor: String? = null,
            codigoTipoDocumento: String? = null,
            nomeTipoDocumento: String? = null,
            parcelas: List<FincreParcela>,
            now: Instant,
        ) = Fincre(
            id = null,
            cnpjEmpresa = cnpjEmpresa,
            codigoEmpresa = codigoEmpresa,
            dataEmissao = dataEmissao,
            documento = documento,
            codigoCondicaoRecebimento = codigoCondicaoRecebimento,
            nomeCondicaoRecebimento = nomeCondicaoRecebimento,
            nomeEmpresa = nomeEmpresa,
            codigoComissao = codigoComissao,
            percentualComissao = percentualComissao,
            codigoCliente = codigoCliente,
            nomeCliente = nomeCliente,
            codigoVendedor = codigoVendedor,
            nomeVendedor = nomeVendedor,
            codigoTipoDocumento = codigoTipoDocumento,
            nomeTipoDocumento = nomeTipoDocumento,
            parcelas = parcelas,
            createdAt = now,
            updatedAt = now,
        )
    }

    fun mergeFromIngestion(
        codigoEmpresa: Long? = null,
        dataEmissao: LocalDate? = null,
        codigoCondicaoRecebimento: String? = null,
        nomeCondicaoRecebimento: String? = null,
        nomeEmpresa: String? = null,
        codigoComissao: Long? = null,
        percentualComissao: BigDecimal? = null,
        codigoCliente: Long? = null,
        nomeCliente: String? = null,
        codigoVendedor: Long? = null,
        nomeVendedor: String? = null,
        codigoTipoDocumento: String? = null,
        nomeTipoDocumento: String? = null,
        parcelas: List<FincreParcela>,
        now: Instant,
    ) = copy(
        codigoEmpresa = codigoEmpresa,
        dataEmissao = dataEmissao,
        codigoCondicaoRecebimento = codigoCondicaoRecebimento,
        nomeCondicaoRecebimento = nomeCondicaoRecebimento,
        nomeEmpresa = nomeEmpresa,
        codigoComissao = codigoComissao,
        percentualComissao = percentualComissao,
        codigoCliente = codigoCliente,
        nomeCliente = nomeCliente,
        codigoVendedor = codigoVendedor,
        nomeVendedor = nomeVendedor,
        codigoTipoDocumento = codigoTipoDocumento,
        nomeTipoDocumento = nomeTipoDocumento,
        parcelas = parcelas,
        updatedAt = now,
    )
}
