package br.com.vertice.emerion_dashboard.domain.product.model

import java.math.BigDecimal
import java.time.Instant

/**
 * Domain model for a Product. Plain Kotlin, no JPA/Jakarta/OpenAPI
 * annotations — this is what use cases and ports operate on. Persistence
 * (JPA entity) and REST (generated DTOs) each have their own mapper to/from
 * this type, so changes to the database schema or the API contract never
 * force changes here (and vice versa).
 */
data class Product(
    val id: Long?,
    val externalId: String,
    val cnpjEmpresa: String,
    val nome: String,
    val descricaoReduzida: String? = null,
    val referenciaInterna: String? = null,
    val ncm: String? = null,
    val cest: String? = null,
    val origemProduto: String? = null,
    val categoria: String? = null,
    val tipo: String? = null,
    val marca: String? = null,
    val unidade: String? = null,
    val unidadeEntrada: String? = null,
    val unidadeSaida: String? = null,
    val pesoLiquido: BigDecimal? = null,
    val pesoBruto: BigDecimal? = null,
    val descontinuado: Boolean? = null,
    val codigoBarras: String? = null,
    val codigoBarrasProprio: String? = null,
    val preco: BigDecimal? = null,
    val preco2: BigDecimal? = null,
    val preco3: BigDecimal? = null,
    val preco4: BigDecimal? = null,
    val preco5: BigDecimal? = null,
    val descontoPadrao: BigDecimal? = null,
    val estoqueDisponivel: BigDecimal? = null,
    val estoqueMinimo: BigDecimal? = null,
    val estoqueMaximo: BigDecimal? = null,
    val estoqueReservado: BigDecimal? = null,
    val estoqueAdquirido: BigDecimal? = null,
    val estoqueAtual: BigDecimal? = null,
    val estoqueRma: BigDecimal? = null,
    val similar: String? = null,
    val quantidadeVolumes: BigDecimal? = null,
    val quantidadeEmbalagem: BigDecimal? = null,
    val localizacao: String? = null,
    val cubagem: BigDecimal? = null,
    val codigoBarrasEmbalagem: String? = null,
    val ibsCClassTrib: String? = null,
    val ibsCst: String? = null,
    val fcpEntrada: BigDecimal? = null,
    val fcpSaida: BigDecimal? = null,
    val ipiSaida: String? = null,
    val ipiEntrada: String? = null,
    val icmSaida: String? = null,
    val icmEntrada: String? = null,
    val icmStSaida: String? = null,
    val icmStEntrada: String? = null,
    val observacao: String? = null,
    val createdAt: Instant,
    val updatedAt: Instant,
) {
    companion object {
        /** Factory for a brand-new product coming from ingestion (no id yet). */
        fun newFromIngestion(
            externalId: String,
            cnpjEmpresa: String,
            nome: String,
            descricaoReduzida: String? = null,
            referenciaInterna: String? = null,
            ncm: String? = null,
            cest: String? = null,
            origemProduto: String? = null,
            categoria: String? = null,
            tipo: String? = null,
            marca: String? = null,
            unidade: String? = null,
            unidadeEntrada: String? = null,
            unidadeSaida: String? = null,
            pesoLiquido: BigDecimal? = null,
            pesoBruto: BigDecimal? = null,
            descontinuado: Boolean? = null,
            codigoBarras: String? = null,
            codigoBarrasProprio: String? = null,
            preco: BigDecimal? = null,
            preco2: BigDecimal? = null,
            preco3: BigDecimal? = null,
            preco4: BigDecimal? = null,
            preco5: BigDecimal? = null,
            descontoPadrao: BigDecimal? = null,
            estoqueDisponivel: BigDecimal? = null,
            estoqueMinimo: BigDecimal? = null,
            estoqueMaximo: BigDecimal? = null,
            estoqueReservado: BigDecimal? = null,
            estoqueAdquirido: BigDecimal? = null,
            estoqueAtual: BigDecimal? = null,
            estoqueRma: BigDecimal? = null,
            similar: String? = null,
            quantidadeVolumes: BigDecimal? = null,
            quantidadeEmbalagem: BigDecimal? = null,
            localizacao: String? = null,
            cubagem: BigDecimal? = null,
            codigoBarrasEmbalagem: String? = null,
            ibsCClassTrib: String? = null,
            ibsCst: String? = null,
            fcpEntrada: BigDecimal? = null,
            fcpSaida: BigDecimal? = null,
            ipiSaida: String? = null,
            ipiEntrada: String? = null,
            icmSaida: String? = null,
            icmEntrada: String? = null,
            icmStSaida: String? = null,
            icmStEntrada: String? = null,
            observacao: String? = null,
            now: Instant,
        ) = Product(
            id = null,
            externalId = externalId,
            cnpjEmpresa = cnpjEmpresa,
            nome = nome,
            descricaoReduzida = descricaoReduzida,
            referenciaInterna = referenciaInterna,
            ncm = ncm,
            cest = cest,
            origemProduto = origemProduto,
            categoria = categoria,
            tipo = tipo,
            marca = marca,
            unidade = unidade,
            unidadeEntrada = unidadeEntrada,
            unidadeSaida = unidadeSaida,
            pesoLiquido = pesoLiquido,
            pesoBruto = pesoBruto,
            descontinuado = descontinuado,
            codigoBarras = codigoBarras,
            codigoBarrasProprio = codigoBarrasProprio,
            preco = preco,
            preco2 = preco2,
            preco3 = preco3,
            preco4 = preco4,
            preco5 = preco5,
            descontoPadrao = descontoPadrao,
            estoqueDisponivel = estoqueDisponivel,
            estoqueMinimo = estoqueMinimo,
            estoqueMaximo = estoqueMaximo,
            estoqueReservado = estoqueReservado,
            estoqueAdquirido = estoqueAdquirido,
            estoqueAtual = estoqueAtual,
            estoqueRma = estoqueRma,
            similar = similar,
            quantidadeVolumes = quantidadeVolumes,
            quantidadeEmbalagem = quantidadeEmbalagem,
            localizacao = localizacao,
            cubagem = cubagem,
            codigoBarrasEmbalagem = codigoBarrasEmbalagem,
            ibsCClassTrib = ibsCClassTrib,
            ibsCst = ibsCst,
            fcpEntrada = fcpEntrada,
            fcpSaida = fcpSaida,
            ipiSaida = ipiSaida,
            ipiEntrada = ipiEntrada,
            icmSaida = icmSaida,
            icmEntrada = icmEntrada,
            icmStSaida = icmStSaida,
            icmStEntrada = icmStEntrada,
            observacao = observacao,
            createdAt = now,
            updatedAt = now,
        )
    }

    /** Applies an ingestion update on top of an existing product, bumping updatedAt. */
    fun mergeFromIngestion(
        cnpjEmpresa: String,
        nome: String,
        descricaoReduzida: String? = null,
        referenciaInterna: String? = null,
        ncm: String? = null,
        cest: String? = null,
        origemProduto: String? = null,
        categoria: String? = null,
        tipo: String? = null,
        marca: String? = null,
        unidade: String? = null,
        unidadeEntrada: String? = null,
        unidadeSaida: String? = null,
        pesoLiquido: BigDecimal? = null,
        pesoBruto: BigDecimal? = null,
        descontinuado: Boolean? = null,
        codigoBarras: String? = null,
        codigoBarrasProprio: String? = null,
        preco: BigDecimal? = null,
        preco2: BigDecimal? = null,
        preco3: BigDecimal? = null,
        preco4: BigDecimal? = null,
        preco5: BigDecimal? = null,
        descontoPadrao: BigDecimal? = null,
        estoqueDisponivel: BigDecimal? = null,
        estoqueMinimo: BigDecimal? = null,
        estoqueMaximo: BigDecimal? = null,
        estoqueReservado: BigDecimal? = null,
        estoqueAdquirido: BigDecimal? = null,
        estoqueAtual: BigDecimal? = null,
        estoqueRma: BigDecimal? = null,
        similar: String? = null,
        quantidadeVolumes: BigDecimal? = null,
        quantidadeEmbalagem: BigDecimal? = null,
        localizacao: String? = null,
        cubagem: BigDecimal? = null,
        codigoBarrasEmbalagem: String? = null,
        ibsCClassTrib: String? = null,
        ibsCst: String? = null,
        fcpEntrada: BigDecimal? = null,
        fcpSaida: BigDecimal? = null,
        ipiSaida: String? = null,
        ipiEntrada: String? = null,
        icmSaida: String? = null,
        icmEntrada: String? = null,
        icmStSaida: String? = null,
        icmStEntrada: String? = null,
        observacao: String? = null,
        now: Instant,
    ) = copy(
        cnpjEmpresa = cnpjEmpresa,
        nome = nome,
        descricaoReduzida = descricaoReduzida,
        referenciaInterna = referenciaInterna,
        ncm = ncm,
        cest = cest,
        origemProduto = origemProduto,
        categoria = categoria,
        tipo = tipo,
        marca = marca,
        unidade = unidade,
        unidadeEntrada = unidadeEntrada,
        unidadeSaida = unidadeSaida,
        pesoLiquido = pesoLiquido,
        pesoBruto = pesoBruto,
        descontinuado = descontinuado,
        codigoBarras = codigoBarras,
        codigoBarrasProprio = codigoBarrasProprio,
        preco = preco,
        preco2 = preco2,
        preco3 = preco3,
        preco4 = preco4,
        preco5 = preco5,
        descontoPadrao = descontoPadrao,
        estoqueDisponivel = estoqueDisponivel,
        estoqueMinimo = estoqueMinimo,
        estoqueMaximo = estoqueMaximo,
        estoqueReservado = estoqueReservado,
        estoqueAdquirido = estoqueAdquirido,
        estoqueAtual = estoqueAtual,
        estoqueRma = estoqueRma,
        similar = similar,
        quantidadeVolumes = quantidadeVolumes,
        quantidadeEmbalagem = quantidadeEmbalagem,
        localizacao = localizacao,
        cubagem = cubagem,
        codigoBarrasEmbalagem = codigoBarrasEmbalagem,
        ibsCClassTrib = ibsCClassTrib,
        ibsCst = ibsCst,
        fcpEntrada = fcpEntrada,
        fcpSaida = fcpSaida,
        ipiSaida = ipiSaida,
        ipiEntrada = ipiEntrada,
        icmSaida = icmSaida,
        icmEntrada = icmEntrada,
        icmStSaida = icmStSaida,
        icmStEntrada = icmStEntrada,
        observacao = observacao,
        updatedAt = now,
    )
}
