package br.com.vertice.emerion_dashboard.domain.liberacao.model

import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate
import java.time.LocalTime

data class Liberacao(
    val id: Long?,
    val cnpjEmpresa: String,
    val codigoEmpresa: Long,
    val dataPedido: LocalDate,
    val numeroPedido: String,
    val numeroLiberacao: Int,
    val dataLiberacao: LocalDate,
    val horaLiberacao: LocalTime,
    val codigoCliente: Long,
    val quantidadeSeparada: BigDecimal,
    val totalLiberadoSemImpostos: BigDecimal,
    val totalLiberadoComImpostos: BigDecimal,
    val situacaoLiberacao: String,
    val codigoVendedor: Long,
    val comissaoLiberacao: BigDecimal,
    val totalCusto: BigDecimal,
    val detalhes: List<LiberacaoDetalhe>,
    val createdAt: Instant,
    val updatedAt: Instant,
) {
    companion object {
        fun newFromIngestion(
            cnpjEmpresa: String,
            codigoEmpresa: Long,
            dataPedido: LocalDate,
            numeroPedido: String,
            numeroLiberacao: Int,
            dataLiberacao: LocalDate,
            horaLiberacao: LocalTime,
            codigoCliente: Long,
            quantidadeSeparada: BigDecimal,
            totalLiberadoSemImpostos: BigDecimal,
            totalLiberadoComImpostos: BigDecimal,
            situacaoLiberacao: String,
            codigoVendedor: Long,
            comissaoLiberacao: BigDecimal,
            totalCusto: BigDecimal,
            detalhes: List<LiberacaoDetalhe>,
            now: Instant,
        ) = Liberacao(
            id = null,
            cnpjEmpresa = cnpjEmpresa,
            codigoEmpresa = codigoEmpresa,
            dataPedido = dataPedido,
            numeroPedido = numeroPedido,
            numeroLiberacao = numeroLiberacao,
            dataLiberacao = dataLiberacao,
            horaLiberacao = horaLiberacao,
            codigoCliente = codigoCliente,
            quantidadeSeparada = quantidadeSeparada,
            totalLiberadoSemImpostos = totalLiberadoSemImpostos,
            totalLiberadoComImpostos = totalLiberadoComImpostos,
            situacaoLiberacao = situacaoLiberacao,
            codigoVendedor = codigoVendedor,
            comissaoLiberacao = comissaoLiberacao,
            totalCusto = totalCusto,
            detalhes = detalhes,
            createdAt = now,
            updatedAt = now,
        )
    }

    fun mergeFromIngestion(
        cnpjEmpresa: String,
        codigoEmpresa: Long,
        dataPedido: LocalDate,
        dataLiberacao: LocalDate,
        horaLiberacao: LocalTime,
        codigoCliente: Long,
        quantidadeSeparada: BigDecimal,
        totalLiberadoSemImpostos: BigDecimal,
        totalLiberadoComImpostos: BigDecimal,
        situacaoLiberacao: String,
        codigoVendedor: Long,
        comissaoLiberacao: BigDecimal,
        totalCusto: BigDecimal,
        detalhes: List<LiberacaoDetalhe>,
        now: Instant,
    ) = copy(
        cnpjEmpresa = cnpjEmpresa,
        codigoEmpresa = codigoEmpresa,
        dataPedido = dataPedido,
        dataLiberacao = dataLiberacao,
        horaLiberacao = horaLiberacao,
        codigoCliente = codigoCliente,
        quantidadeSeparada = quantidadeSeparada,
        totalLiberadoSemImpostos = totalLiberadoSemImpostos,
        totalLiberadoComImpostos = totalLiberadoComImpostos,
        situacaoLiberacao = situacaoLiberacao,
        codigoVendedor = codigoVendedor,
        comissaoLiberacao = comissaoLiberacao,
        totalCusto = totalCusto,
        detalhes = detalhes,
        updatedAt = now,
    )
}
