package br.com.vertice.emerion_dashboard.application.notification.creation.model

import br.com.vertice.emerion_dashboard.domain.notification.model.NotificationCategory
import br.com.vertice.emerion_dashboard.domain.notification.model.NotificationPriority

/**
 * Command to create a new notification for a single user. Used internally
 * by other application services (e.g. an ingestion service flagging an
 * order that needs approval) — there is no REST endpoint for this, since
 * notifications are never pushed by emerion-load-service or the React app,
 * only generated by this API's own business logic.
 */
data class CreateNotificationCommand(
    val userId: String,
    val name: String,
    val description: String,
    val category: NotificationCategory,
    val priority: NotificationPriority = NotificationPriority.MEDIUM,
    val referenceType: String? = null,
    val referenceId: String? = null,
    val actionUrl: String? = null,
)
